#!/bin/sh
load="/proc/loadavg"
temp="/sys/devices/virtual/thermal/thermal_zone0/temp"
bat="/sys/class/power_supply/BAT0/capacity"
tmp="/tmp/xstatus"
get_load()
{
	cat $load | cut -d ' ' -f 1
}
get_temp()
{
	echo $(($(cat $temp)/1000))
}
get_bat()
{
	cat $bat
}
trap exit INT QUIT TERM HUP
trap "rm -f $tmp" EXIT
while true; do
	echo "`get_load` | `get_temp`C | `get_bat`%" > $tmp
	sleep 5
done
